### ISSUE TITLE
Update ELIXIR logo in landing page

### ISSUE THREAD

**Issue by scapella** [inab/openEBench-nuxt#45]
ELIXIR logo used in the landing page is incorrect as it points out to a specific resource (ELIXIR AAI) > ELIXIR Authentification and Authorization Infrastructure. I'd suggest using the correct one located for instance at https://elixir-europe.org/system/files/white-orange-logo.png

**Comment by dominikbruechner** [comment]
https://github.com/inab/openEBench-nuxt/commit/4eb30a68003f9970810fe6913ff470747f445691

**Comment by dominikbruechner** [comment]
done with mentioned commit
