### ISSUE TITLE
Make the tool more reliable

### ISSUE THREAD

**Issue by celalvrom** [inab/openEBench-nuxt#631]
When the tool describes whether or not each FAIR item has passed or failed, it would be great finding a description of why that result was achieved. For example, if it is Findable, which items were reviewed for it and which items were met.

**Comment by EvaMart** [comment]
That is very true; the user should be given better feedback during the evaluation. Especially when an indicator fails, the user is left a bit clueless. 

I will think of the best way to add this functionality and try to implement it in the next iterations. 

Thanks, @celalvrom!

**Comment by EvaMart** [comment]
Detailed logs of how the decision was reached are now in production 🎉
