### ISSUE TITLE
[Evaluator] Unable to run tool when using metadata file URL or upload as input

### ISSUE THREAD

**Issue by abnerbog** [inab/openEBench-nuxt#658]
**Bug description:**

The [FAIR evaluator tool](https://openebench.bsc.es/observatory/Evaluation/) is unable to calculate FAIR scores when using a metadata file as input.

**To reproduce:**

1. Go to the [FAIRsoft evaluator app](https://openebench.bsc.es/observatory/Evaluation/)
2. In Step 1, select 'Metadata file' and 'Enter URL' as the metadata source 
3. Enter the URL: 'https://raw.githubusercontent.com/inab/observatory-api/a825f37ecf6d557c9f7ad892da05ff32cebd35bc/app/helpers/metadata.jsonld'
     - The same issue occurs when uploading the metadata as a file instead of entering a URL

**Unexpected output:**

When the metadata source is entered as a URL, the tool hangs on step 3:

![image](https://github.com/user-attachments/assets/4139e571-d818-4f51-b453-e5a653ebcae9)

When the metadata source is entered as a file, the tool does not retrieve any metadata and is unable to calculate the FAIR scores.

![image](https://github.com/user-attachments/assets/7cbf51c1-60cf-4ab3-ad15-52615edb150f)

**Environment:**  

Device: Dell laptop (x64)   
OS: Windows 11 Pro  
Browser: Google Chrome

**Comment by EvaMart** [comment]
Apologies for the delay; I completely missed this! I'll review it and get back to you soon.

**Comment by abnerbog** [comment]
Thanks so much! To add some further context here -- I also tried downloading the metadata in JSON-LD format through the evaluator tool in the 'Results' step after using a GitHub URL as input (e.g. 'https://github.com/inab/oeb-visualizations'), and then using this file as input into the evaluator in Step 1. When I go to use the tool with this JSON-LD input, I can proceed to Step 3 ('Edit the metadata if needed') as expected but the tool hangs when attempting to evaluate FAIR indicators in Step 4 ('Results').

**Comment by EvaMart** [comment]
Hi Abner,

Thank you for your feedback. It appears that the file you were trying to upload is in an older format, which is no longer supported. As part of a major update this summer, we modified the tool to use the [maSMP format](https://zbmed-semtec.github.io/maSMPs/). Unfortunately, this means that files in the previous format are now incompatible—apologies for any inconvenience this may have caused. 

I also resolved a few additional issues, and the tool should now work with files in the maSMP format, whether uploaded directly from your local filesystem or through a URL. If you have any questions or run into further issues, please don’t hesitate to reach out 🙏.
