### ISSUE TITLE
Partner logos in movement

### ISSUE THREAD

**Issue by EvaAlloza** [inab/openEBench-nuxt#83]
I would suggest that the partner logos move to improve their visibility. Otherwise, some partners will be always hidden and only appear if the user actively clicks the arrows.

**Comment by dominikbruechner** [comment]
Resolved with https://github.com/inab/openEBench-nuxt/commit/a87c6f0c2cd082d3f51f4a76eed0ee8cdfc4668d
Live with Release 0.1.2
